apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  DB_USER_REPAIR: cG9zdGdyZXM=
  DB_PASSWORD_REPAIR: MTIzNA==
  DB_USER_VEHICLE: cG9zdGdyZXM=
  DB_PASSWORD_VEHICLE: MTIzNA==
  DB_USER_RECEIPT: cG9zdGdyZXM=
  DB_PASSWORD_RECEIPT: MTIzNA==
  DB_USER_REPORT: cG9zdGdyZXM=
  DB_PASSWORD_REPORT: MTIzNA==