apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt-deployment
  labels:
    app: receipt-deployment
spec:
  selector:
    matchLabels:
      app: receipt-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: receipt-deployment
    spec:
      containers:
        - name: receipt-service
          image: fernandosolispaz/receipt-service
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_RECEIPT
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_RECEIPT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_RECEIPT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_RECEIPT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_RECEIPT